#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional


def _slugify_to_identifier(text: str, *, max_len: int = 40) -> str:
    """Return a conservative identifier: [a-z0-9_], no leading digit."""
    normalized = text.strip().lower()
    normalized = re.sub(r"[^a-z0-9]+", "_", normalized)
    normalized = re.sub(r"_+", "_", normalized).strip("_")
    if not normalized:
        normalized = "demo"
    if normalized[0].isdigit():
        normalized = f"w_{normalized}"
    return normalized[:max_len]


@dataclass
class IdFactory:
    counter: int = 0

    def new(self, prefix: str) -> str:
        self.counter += 1
        safe_prefix = re.sub(r"[^A-Za-z0-9_]+", "_", prefix).strip("_") or "step"
        return f"{safe_prefix}_{self.counter:03d}"


def _yaml_quote(s: str) -> str:
    # Simple double-quote quoting for single-line YAML scalars.
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _indent(lines: List[str], spaces: int) -> List[str]:
    pad = " " * spaces
    return [pad + line if line else "" for line in lines]


def _render_header(workflow_id: str, naming_note: str, variables: Dict[str, str]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    header_lines: List[str] = [
        "# Generated by maf-decalarative-yaml/scripts/generate_workflow_yaml.py",
        f"# Generated at (UTC): {now}",
        "#",
        "# NAMING CONVENTIONS",
        f"# - workflow trigger id: {workflow_id}",
        f"# - action ids: {naming_note}",
        "#",
        "# VARIABLE TABLE (workflow-scoped)",
    ]

    for name in sorted(variables.keys()):
        header_lines.append(f"# - {name}: {variables[name]}")

    header_lines.append("")
    return "\n".join(header_lines)


def generate_workflow_yaml(
    *,
    requirement: str,
    workflow_id: str,
    planner_agent: Optional[str],
    executor_agent: str,
    use_status_thread: bool,
) -> str:
    ids = IdFactory()

    variables: Dict[str, str] = {
        "Local.InputTask": "Embedded requirement passed to this generator (runner-friendly)",
        "Local.ExecutionPrompt": "Final prompt sent to the executor agent",
        "Local.FinalResponse": "Executor agent output messages",
    }

    if planner_agent:
        variables["Local.PlanningPrompt"] = "Prompt sent to the planner agent"
        variables["Local.Plan"] = "Planner agent output messages"

    if use_status_thread:
        variables["Local.StatusConversationId"] = "Conversation id for planning/status messages"

    naming_note = "<prefix>_<001..N> (monotonic, unique across the workflow)"

    header = _render_header(workflow_id, naming_note, variables)

    input_task_lines = (requirement or "").strip().splitlines() or [""]

    # We intentionally rely on the same placeholder style used in official samples
    # (e.g., {Local.InputTask}, {MessageText(Local.Plan)}) inside block scalars.
    planning_prompt_lines = [
        "# PLANNING TASK",
        "Create a concise plan (bullet points) to satisfy the following user request:",
        "",
        "{Local.InputTask}",
        "",
        "Constraints:",
        "- Keep it short and actionable.",
        "- Prefer steps that are feasible in this environment.",
    ]

    execution_prompt_lines = [
        "# TASK",
        "Address the following user request:",
        "",
        "{Local.InputTask}",
        "",
    ]

    if planner_agent:
        execution_prompt_lines += [
            "# PLAN",
            "Follow this plan as best as possible:",
            "",
            "{MessageText(Local.Plan)}",
            "",
        ]

    execution_prompt_lines += [
        "# OUTPUT",
        "Provide a direct, complete answer.",
    ]

    yaml_lines: List[str] = []
    yaml_lines.append("kind: Workflow")
    yaml_lines.append("trigger:")
    yaml_lines += _indent(["kind: OnConversationStart"], 2)
    yaml_lines += _indent([f"id: {workflow_id}"], 2)
    yaml_lines += _indent(["actions:"], 2)

    # Set input (embed the requirement so the workflow is runnable in the local runner)
    yaml_lines += _indent(
        [
            "- kind: SetTextVariable",
            f"  id: {ids.new('set_input')}",
            "  displayName: Embed user requirement",
            "  variable: Local.InputTask",
            "  value: |-",
        ],
        4,
    )
    yaml_lines += _indent(input_task_lines, 8)
    yaml_lines.append("")

    yaml_lines += _indent(
        [
            "- kind: SendActivity",
            f"  id: {ids.new('send_status')}",
            "  activity: " + _yaml_quote("Working on it..."),
            "",
        ],
        4,
    )

    if use_status_thread:
        yaml_lines += _indent(
            [
                "- kind: CreateConversation",
                f"  id: {ids.new('create_status_thread')}",
                "  conversationId: Local.StatusConversationId",
                "",
            ],
            4,
        )

    if planner_agent:
        # Planning prompt as text variable
        yaml_lines += _indent(
            [
                "- kind: SetTextVariable",
                f"  id: {ids.new('set_planning_prompt')}",
                "  displayName: Build planning prompt",
                "  variable: Local.PlanningPrompt",
                "  value: |-",
            ],
            4,
        )
        yaml_lines += _indent(planning_prompt_lines, 8)
        yaml_lines.append("")

        # Invoke planner
        invoke_planner: List[str] = [
            "- kind: InvokeAzureAgent",
            f"  id: {ids.new('invoke_planner')}",
            "  displayName: Create a plan",
        ]
        if use_status_thread:
            invoke_planner.append("  conversationId: =Local.StatusConversationId")
        invoke_planner += [
            "  agent:",
            f"    name: {planner_agent}",
            "  input:",
            "    messages: =UserMessage(Local.PlanningPrompt)",
            "  output:",
            "    messages: Local.Plan",
            "",
        ]
        yaml_lines += _indent(invoke_planner, 4)

    # Execution prompt as text variable
    yaml_lines += _indent(
        [
            "- kind: SetTextVariable",
            f"  id: {ids.new('set_execution_prompt')}",
            "  displayName: Build execution prompt",
            "  variable: Local.ExecutionPrompt",
            "  value: |-",
        ],
        4,
    )
    yaml_lines += _indent(execution_prompt_lines, 8)
    yaml_lines.append("")

    # Invoke executor
    invoke_executor: List[str] = [
        "- kind: InvokeAzureAgent",
        f"  id: {ids.new('invoke_executor')}",
        "  displayName: Generate final response",
        "  agent:",
        f"    name: {executor_agent}",
        "  input:",
        "    messages: =UserMessage(Local.ExecutionPrompt)",
        "  output:",
        "    autoSend: true",
        "    messages: Local.FinalResponse",
        "",
        "- kind: EndConversation",
        f"  id: {ids.new('end')}",
        "",
    ]
    yaml_lines += _indent(invoke_executor, 4)

    # (Optional) Include the raw requirement in a comment block for traceability.
    requirement_lines = [
        "# REQUIREMENT (raw)",
        *[f"# {line}" for line in (requirement or "").strip().splitlines()],
        "",
    ]

    return header + "\n".join(yaml_lines) + "\n" + "\n".join(requirement_lines)


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a starter Microsoft Agent Framework declarative Workflow YAML from a natural-language requirement. "
            "The output includes naming conventions, auto-generated action ids, and a variable table as comments."
        )
    )
    parser.add_argument(
        "--requirement",
        required=True,
        help="Natural-language requirement to embed into the workflow.",
    )
    parser.add_argument(
        "--out",
        help="Optional output path. If omitted, prints to stdout.",
    )
    parser.add_argument(
        "--workflow-id",
        help="Optional trigger id. Defaults to workflow_<slug> derived from the requirement.",
    )
    parser.add_argument(
        "--planner-agent",
        default="PlannerAgent",
        help="Planner agent name. Ignored when --no-planner is set. Default: PlannerAgent",
    )
    parser.add_argument(
        "--executor-agent",
        default="SummaryAgent",
        help="Executor agent name for the final response. Default: SummaryAgent",
    )
    parser.add_argument(
        "--no-planner",
        action="store_true",
        help="Generate a single-agent workflow (skip planning step).",
    )
    parser.add_argument(
        "--use-status-thread",
        action="store_true",
        help="Create a separate conversation thread for planning/status messages.",
    )

    args = parser.parse_args(argv)

    requirement = str(args.requirement)
    slug = _slugify_to_identifier(requirement)
    workflow_id = args.workflow_id or f"workflow_{slug}"

    planner_agent = None if args.no_planner else str(args.planner_agent)
    executor_agent = str(args.executor_agent)

    yaml_text = generate_workflow_yaml(
        requirement=requirement,
        workflow_id=workflow_id,
        planner_agent=planner_agent,
        executor_agent=executor_agent,
        use_status_thread=bool(args.use_status_thread),
    )

    if args.out:
        out_path = Path(args.out)
        out_path.write_text(yaml_text, encoding="utf-8")
        print(f"Wrote workflow YAML to: {out_path}")
    else:
        print(yaml_text)

    return 0


if __name__ == "__main__":
    raise SystemExit(main(__import__("sys").argv[1:]))
